# Generated by Django 2.0.4 on 2018-07-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstApplication.Animal')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
            bases=('firstApplication.animal',),
        ),
    ]
